---
# Created By : Krutika
# Date: 10 april 2023
# Purpose:  This YAML will add,commit and push specific files

- name: add commit and push files
  hosts:  localhost

  tasks:

  - name: add and commit VERSION and .bumpversion.cfg
    git_acp:
      path: \home\krutika_bhise\workdir\personal_repo\deployment_commits\develop\deployment-commits\
      comment: "add  VERSION and .bumpversion.cfg"
      add: [ "VERSION", ".bumpversion.cfg" ]
      branch: develop
      pull: true
      # push: true
      # push_force: true
      mode: ssh
      url: "git@github.com:krutikabhise/deployment-commits.git"

  - name: push files
    ansible.builtin.command:
      cmd: "git push"
      chdir: /home/krutika_bhise/workdir/personal_repo/deployment_commits/main/deployment-commits

      
        

