---
# Created By : Krutika
# Date: 25 april 2023
# Purpose:  This YAML will add,commit and push specific files

- name: add commit and push files
  hosts:  localhost

  tasks:
    
    - name: pull files
      ansible.builtin.git:
        repo: "git@github.com:krutikabhise/deployment-commits.git"
        dest: /home/krutika_bhise/workdir/personal_repo/deployment_commits/develop/deployment-commits
        # update: yes
        version: devlop
        

    - name: add files
      ansible.builtin.command:
        cmd: "git add VERSION, .bumpversion.cfg"
        chdir: /home/krutika_bhise/workdir/personal_repo/deployment_commits/develop/deployment-commits
        
    - name: commit files
      ansible.builtin.command:
        cmd: "git commit -m 'modified VERSION and .bumpversion.cfg'"
        chdir: /home/krutika_bhise/workdir/personal_repo/deployment_commits/develop/deployment-commits

    - name: pull files
      ansible.builtin.command:
        url: "git@github.com:krutikabhise/deployment-commits.git"
        chdir: /home/krutika_bhise/workdir/personal_repo/deployment_commits/develop/deployment-commits
        update: yes
        version: develop

    - name: push files
      ansible.builtin.command:
        cmd: "git push"
        chdir: /home/krutika_bhise/workdir/personal_repo/deployment_commits/develop/deployment-commits
        
    - name: merge files
      ansible.builtin.command:
        cmd: git merge origin/master
        chdir: /home/krutika_bhise/workdir/personal_repo/deployment_commits/main/deployment-commits

    - name: push files
      ansible.builtin.command:
        cmd: "git push"
        chdir: /home/krutika_bhise/workdir/personal_repo/deployment_commits/main/deployment-commits