---
# Created By : Krutika
# Date: 25 april 2023
# Purpose:  This YAML will add,commit and push specific files

- name: add commit and push files
  hosts:  localhost

  tasks:
  
    - name: add tag
      ansible.builtin.shell:
        cmd: "bump2version --tag patch"
        chdir: /home/krutika_bhise/workdir/personal_repo/deployment_commits/develop/deployment-commits
      
    - name: add files
      ansible.builtin.shell:
        cmd: git add VERSION .bumpversion.cfg && git commit -m "modified VERSION and .bumpversion.cfg"
        chdir: /home/krutika_bhise/workdir/personal_repo/deployment_commits/develop/deployment-commits

    - name: pull files
      ansible.builtin.command:
        cmd: git pull
        chdir: /home/krutika_bhise/workdir/personal_repo/deployment_commits/develop/deployment-commits
        update: yes
        version: develop

    - name: push files
      ansible.builtin.command:
        cmd: git push
        chdir: /home/krutika_bhise/workdir/personal_repo/deployment_commits/develop/deployment-commits